spring:
  datasource:
    url: jdbc:h2:mem:authDb
    username: ensias
    password: ensias
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update # or create-drop if you want to recreate the database on every startup
