spring:
  application:
    name: authentication-service
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

jwt:
  secret: ${random.value}