server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://yassinouhadi:9ZdBVB78UH6Tb4O7@eldycare-cluster.xcn4yoa.mongodb.net/eldycare?retryWrites=true&w=majority
  application:
    name: notification-service

amqp:
  notif:
    queue: notification-queue
    exchange: notification-exchange
    routingkey: 'notification.#.*'

#notification:
#  rabbitmq:
#    notificationQueue: notificationQueue
#    relativeQueue: relativeQueue
#    exchange: amq.topic
#    notificationRoutingkey: 'notificationkey.#.*'
#    relativeRoutingKey: 'relativeKey.#.*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

