version: '3.0'

volumes:
  postgres-data:
  neo4j-data:
  mongo-data-notification:
  mongo-data-reminder:

services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: eldycare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongodb-notification:
    container_name: mongodb-notification
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data-notification:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  mongo-express-notification:
    container_name: mongo-express-notification
    image: mongo-express:latest
    ports:
      - 9901:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongodb-notification

  mongodb-reminder:
    container_name: mongodb-reminder
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongo-data-reminder:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
  mongo-express-reminder:
    container_name: mongo-express-reminder
    image: mongo-express:latest
    ports:
      - 9902:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_SERVER: mongodb-reminder

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/saga-pablo-lagoon-java-license-4169
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
